### ISSUE TITLE
Define guard

### ISSUE THREAD

**Issue by kamov** [raniesantos/vue-routisan#43]
Can you please explain how to define the guard?

Does this is in relation with laravel guard auth? Or?

Does this is enough stable to be used in production?

Thanks!

**Comment by blogui91** [comment]
Hello, I will share my opinion, since the author has not responded.

**Can you please explain how to define the guard?**
A guard may work like a middleware, the most basic usage is for authentication, or for setting some information before go next route. You can take a look into this link https://github.com/blogui91/quasar-oauth-laravel/tree/master/src/router
If this is still not understandable please check this other https://router.vuejs.org/guide/advanced/navigation-guards.html#global-guards

**Does this is in relation with laravel guard auth?**
Since this package is inspired in laravel routes, yes, both have the same finality.

**Does this is enough stable to be used in production?**
Yes, it's ready for production, I have three projects using this package, until now everything is okay. 

The objective of this package is to make more understandable the declaration of routes for more information
I have a public repo using this library, please take a look how i used the guards 
I hope i can help you.

**Comment by raniesantos** [comment]
Hi, sorry for not responding immediately. I just now found out that my settings on this repo were set to Unwatched for some reason so I wasn't getting notified of this issue.

Read the vue-router documentation, specifically the part about [Navigation Guards](https://router.vuejs.org/guide/advanced/navigation-guards.html#per-route-guard). The guards I refer to in the README is the same as the one in the Vue docs.

This package is based on Laravel's routing system, but it is not dependent on having Laravel as your backend. As long as you are using vue-router, this should work regardless of what other technology you use in your stack.

I will be closing this issue now. Thank you @blogui91 for providing answers in my absence.
